spring:
  application:
    name: query-dict-api
  data:
    mongodb:
      uri: 'mongodb+srv://admin:<admindb>@clusterdict.lns9f2j.mongodb.net/?retryWrites=true&w=majority&appName=ClusterDict'
      database: dictdb
