spring:
  application:
    name: query-dict-api
  datasource:
    url:
      jdbc:
        h2:
          mem: dictdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
h2:
console:
  enabled: true
server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
